import type { TerraLayerDefinition } from "@/types/layer";

/**
 * Master layer catalog (spec §7 / §13). This lists the intended catalog as
 * *categories with honest availability*, NOT a promise that every feed is live
 * (spec §7 intro, §13, §33). Each entry declares its implementation status:
 *
 *   - "available"             → renders now (Phase 1: only the simulated demo)
 *   - "planned"               → catalogued, arrives in a later phase
 *   - "requires-credentials"  → needs a provider key/terms before it can ship
 *
 * The UI shows this status so users are never misled about coverage.
 */
export const LAYER_CATALOG: TerraLayerDefinition[] = [
  // ── LIVE TRACKING ────────────────────────────────────────────────────────
  {
    id: "demo-entities",
    name: "Demo Entities (Simulated)",
    category: "Live tracking",
    description:
      "A small set of clearly-labeled simulated points to demonstrate selection, the entity inspector, and feed-status behavior. Not real data.",
    icon: "sparkles",
    enabledByDefault: true,
    supportedViews: ["globe"],
    sourceIds: ["terra-sim"],
    updateMode: "live",
    refreshIntervalSeconds: 3,
    attribution: "Simulated demonstration data generated locally by TERRA.",
    coverageDescription: "Synthetic — a handful of fixed sample locations. No real-world coverage.",
    knownLimitations: [
      "All values are invented for demonstration and are NOT real observations.",
      "Present only so the UI can be exercised before real feeds are wired up.",
    ],
    sensitivity: "public",
    implementationStatus: "available",
    simulated: true,
    defaultStyle: { color: "#70A7FF", pointSize: 12 },
  },
  {
    id: "aircraft",
    name: "Aircraft",
    category: "Live tracking",
    description: "Live aircraft positions from a permitted public/commercial ADS-B feed.",
    icon: "plane",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: ["opensky"],
    updateMode: "live",
    refreshIntervalSeconds: 10,
    coverageDescription: "Coverage varies by receiver network, region, altitude, and provider.",
    knownLimitations: [
      "Requires provider access; anonymous feeds are rate-limited.",
      "Some aircraft may be missing, delayed, or filtered by the provider.",
    ],
    sensitivity: "public",
    implementationStatus: "requires-credentials",
    defaultStyle: { color: "#FFC66D" },
  },
  {
    id: "satellites",
    name: "Satellites",
    category: "Live tracking",
    description: "Orbital objects visualized from public orbital elements (computed estimates, not live telemetry).",
    icon: "satellite",
    enabledByDefault: false,
    supportedViews: ["globe"],
    sourceIds: ["celestrak"],
    updateMode: "periodic",
    coverageDescription: "Publicly cataloged objects. Position accuracy degrades as orbital elements age.",
    knownLimitations: [
      "Positions are computed from orbital elements, not direct telemetry.",
      "Classified/non-public objects are not available.",
    ],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#A78BFA" },
  },
  {
    id: "ships",
    name: "Ships",
    category: "Live tracking",
    description: "AIS vessel positions from a permitted maritime feed.",
    icon: "ship",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "live",
    coverageDescription: "AIS coverage is not universal and may be delayed or absent.",
    knownLimitations: ["Requires a licensed AIS provider.", "Land vs satellite AIS coverage differs."],
    sensitivity: "public",
    implementationStatus: "requires-credentials",
    defaultStyle: { color: "#55D6E8" },
  },
  {
    id: "public-transit",
    name: "Public transit",
    category: "Live tracking",
    description: "Transit vehicles from open GTFS-Realtime feeds.",
    icon: "bus",
    enabledByDefault: false,
    supportedViews: ["map"],
    sourceIds: [],
    updateMode: "live",
    coverageDescription: "Availability varies greatly by agency and feed license.",
    knownLimitations: ["Each agency feed has its own license and coverage."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#54D6A0" },
  },

  // ── WEATHER ──────────────────────────────────────────────────────────────
  {
    id: "severe-alerts",
    name: "Weather alerts",
    category: "Weather",
    description: "Active watches, warnings, and advisories from NOAA/NWS (US).",
    icon: "alert",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: ["nws-alerts"],
    updateMode: "periodic",
    refreshIntervalSeconds: 120,
    attribution: "Alerts courtesy of NOAA / National Weather Service.",
    termsUrl: "https://www.weather.gov/documentation/services-web-api",
    coverageDescription: "United States only (NOAA/NWS). Other regions require additional sources.",
    knownLimitations: [
      "A visualization is never a substitute for official emergency instructions.",
      "Alerts that reference NWS zones without an inline map shape are counted but not drawn.",
    ],
    sensitivity: "public",
    implementationStatus: "available",
    defaultStyle: { color: "#FF737D" },
  },
  {
    id: "weather-radar",
    name: "Radar",
    category: "Weather",
    description: "Radar reflectivity raster overlay where available.",
    icon: "radar",
    enabledByDefault: false,
    supportedViews: ["map"],
    sourceIds: [],
    updateMode: "periodic",
    coverageDescription: "Regional radar coverage; not global.",
    knownLimitations: ["Raster tiles require a licensed provider."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: {},
  },
  {
    id: "weather-observations",
    name: "Observations",
    category: "Weather",
    description: "Point weather observations (temperature, wind, pressure) from public APIs.",
    icon: "thermometer",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "periodic",
    coverageDescription: "Station coverage varies by region.",
    knownLimitations: ["Observation is separated from forecast; forecasts are not guaranteed."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#70A7FF" },
  },

  // ── EARTH EVENTS ─────────────────────────────────────────────────────────
  {
    id: "earthquakes",
    name: "Earthquakes",
    category: "Earth events",
    description: "Recent earthquakes with magnitude, depth, and origin time from USGS.",
    icon: "activity",
    enabledByDefault: false,
    supportedViews: ["globe", "map", "timeline"],
    sourceIds: ["usgs-earthquakes"],
    updateMode: "periodic",
    refreshIntervalSeconds: 300,
    attribution: "Earthquake data courtesy of the U.S. Geological Survey.",
    termsUrl: "https://www.usgs.gov/information-policies-and-instructions/crediting-usgs",
    coverageDescription: "Global; smaller events have regional detection thresholds.",
    knownLimitations: [
      "Early magnitudes/locations are automatic and may be revised as more data arrives.",
      "Depth and magnitude uncertainty vary by region and network.",
    ],
    sensitivity: "public",
    implementationStatus: "available",
    defaultStyle: { color: "#FFC66D" },
  },
  {
    id: "wildfires",
    name: "Wildfires",
    category: "Earth events",
    description: "Active fire detections from NASA FIRMS.",
    icon: "flame",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: ["nasa-firms"],
    updateMode: "periodic",
    coverageDescription: "Satellite thermal detections; near-real-time with latency.",
    knownLimitations: ["A detection is a thermal anomaly, not a confirmed fire perimeter.", "Requires a free FIRMS MAP_KEY."],
    sensitivity: "public",
    implementationStatus: "requires-credentials",
    defaultStyle: { color: "#FF737D" },
  },
  {
    id: "volcanoes",
    name: "Volcanoes",
    category: "Earth events",
    description: "Volcano alerts and reported activity from authoritative sources.",
    icon: "mountain",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "periodic",
    coverageDescription: "Depends on monitoring agency coverage.",
    knownLimitations: ["Reporting cadence varies by observatory."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#FFC66D" },
  },

  // ── SPACE ────────────────────────────────────────────────────────────────
  {
    id: "space-stations",
    name: "Space stations",
    category: "Space",
    description: "ISS and selected stations positioned from public orbital data.",
    icon: "orbit",
    enabledByDefault: false,
    supportedViews: ["globe"],
    sourceIds: ["celestrak"],
    updateMode: "periodic",
    coverageDescription: "Computed from orbital elements; not live telemetry.",
    knownLimitations: ["Predicted position; error grows with element age."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#55D6E8" },
  },
  {
    id: "day-night",
    name: "Day / night",
    category: "Space",
    description: "Computed day/night terminator and sub-solar point.",
    icon: "sun",
    enabledByDefault: false,
    supportedViews: ["globe"],
    sourceIds: [],
    updateMode: "live",
    coverageDescription: "Computed astronomical value; global.",
    knownLimitations: ["Purely computed; labeled as such."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: {},
  },
  {
    id: "launches",
    name: "Launches",
    category: "Space",
    description: "Upcoming and recent orbital launches from public manifests.",
    icon: "rocket",
    enabledByDefault: false,
    supportedViews: ["globe", "timeline"],
    sourceIds: [],
    updateMode: "periodic",
    coverageDescription: "Depends on public launch manifest sources.",
    knownLimitations: ["Schedules change frequently."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#A78BFA" },
  },

  // ── ENVIRONMENT ──────────────────────────────────────────────────────────
  {
    id: "air-quality",
    name: "Air quality",
    category: "Environment",
    description: "PM2.5/PM10 and other air-quality station measurements.",
    icon: "wind",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "periodic",
    coverageDescription: "Station coverage is uneven and not global.",
    knownLimitations: ["Does not imply uniform global measurement coverage."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#54D6A0" },
  },

  // ── PLACES & INFRASTRUCTURE ──────────────────────────────────────────────
  {
    id: "terrain",
    name: "Terrain & elevation",
    category: "Places & infrastructure",
    description: "3D terrain / elevation base (requires a terrain provider).",
    icon: "layers",
    enabledByDefault: false,
    supportedViews: ["globe"],
    sourceIds: ["cesium-ion"],
    updateMode: "static",
    coverageDescription: "Global terrain requires Cesium Ion or an equivalent terrain source.",
    knownLimitations: ["Needs a Cesium Ion token; falls back to a smooth ellipsoid otherwise."],
    sensitivity: "public",
    implementationStatus: "requires-credentials",
    defaultStyle: {},
  },
  {
    id: "cities",
    name: "Cities",
    category: "Places & infrastructure",
    description: "Populated places and labels.",
    icon: "building",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: ["open-meteo-geocoding"],
    updateMode: "static",
    coverageDescription: "Populated-place gazetteer.",
    knownLimitations: ["Static reference data, not live status."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: {},
  },

  // ── PUBLIC CAMERAS ───────────────────────────────────────────────────────
  {
    id: "public-cameras",
    name: "Public cameras",
    category: "Public cameras",
    description:
      "Only intentionally-public webcams that permit linking/embedding. TERRA never scans for exposed cameras or bypasses access controls.",
    icon: "camera",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "static",
    coverageDescription: "Only publishers who permit reuse; strictly no private feeds.",
    knownLimitations: [
      "No private CCTV, home, or security cameras — ever.",
      "A camera is not claimed 'live' unless a reliable status feed confirms it.",
    ],
    sensitivity: "restricted",
    implementationStatus: "planned",
    defaultStyle: {},
  },

  // ── MY DATA ──────────────────────────────────────────────────────────────
  {
    id: "my-places",
    name: "Saved places",
    category: "My data",
    description: "Your bookmarked locations and personal markers.",
    icon: "bookmark",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "static",
    coverageDescription: "Local to this browser until accounts/sync are added.",
    knownLimitations: ["Kept locally; not synced in Phase 1."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: { color: "#70A7FF" },
  },
  {
    id: "imported-files",
    name: "Imported files",
    category: "My data",
    description: "GeoJSON / KML / GPX / CSV layers you import (with validation).",
    icon: "upload",
    enabledByDefault: false,
    supportedViews: ["globe", "map"],
    sourceIds: [],
    updateMode: "static",
    coverageDescription: "Whatever you import; validated for size and format.",
    knownLimitations: ["Import & validation arrive in Phase 7."],
    sensitivity: "public",
    implementationStatus: "planned",
    defaultStyle: {},
  },
];

/** Ordered category list for the catalog UI (spec §13). */
export const CATEGORY_ORDER: string[] = [
  "Live tracking",
  "Weather",
  "Earth events",
  "Space",
  "Environment",
  "Places & infrastructure",
  "Public cameras",
  "My data",
];

export function getLayer(id: string): TerraLayerDefinition | undefined {
  return LAYER_CATALOG.find((l) => l.id === id);
}
